### ISSUE TITLE
Search for datasets by license

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1029]
We currently store license data in the `licenses` field for some datasets. It would be useful to be able to find datasets matching a particular license or set of licenses, e.g.,

CLI:
```
$ retriever ls -l MIT GPL
```

Python interface:
```
>>> retriever.dataset_names(licenses = ["MIT", "GPL"])
```

This should return a list of datasets with one of the specified licenses.

Similar CLI functionality exists at https://github.com/weecology/retriever/blob/master/retriever/__main__.py#L140 for seaching based on keywords.

**Comment by adhaamehab** [comment]
Hi @ethanwhite 
I will to work on this issue. How do I get started?

**Comment by henrykironde** [comment]
Hi @adhaamehab the best way to start is by looking at the developer docs on how to set up the environment. Let me know if you need any help when setting up the environment

**Comment by adhaamehab** [comment]
Hi @henrykironde  @ethanwhite 
I'm a bit confused with issue #969 
```
retriever ls -l MIT
``` 
 will print

```Available datasets : 1

1. Masses of Mammals (Smith et al. 2003)
mammal-masses
['mammals', 'literature-compilation', 'size']
```
so what should this command output ? how should I differentiate between keyword and license? 
should I first check if the input -or set of inputs- is a licenses ?

**Comment by henrykironde** [comment]
We are using `argparse` in `retriever/retriever/lib/get_opts.py` to parse arguments.
Right now, for this specific command `retriever ls -l MIT`, Retriever searches for dataset that have keywords that are like MIT.
_We need to make it better actually, because MIT is not so close to the results provided._

However, If we add licenses, then we should adjust the code to look for datasets(scripts) that also contain that given license.

There are two designs we could follow

1. Using `retriever ls -l `  like in retriever ls -l MIT  and we just add some logic to look for licenses
2. Using a new option for only licenses. e.g `retriever ls --license MIT` or `retriever ls -c MIT`

I think the first option would be good for now. We can change it later, if we want something specific. 
Let me know if that sounds clear
