### ISSUE TITLE
Add performance benchmark for data retriever

### ISSUE THREAD

**Issue by adhaamehab** [weecology/retriever#1112]
To improve data retriever efficiency for out-of-memory scale data and performance in general first, We should determine the heavy parts in the source code.

Using [Profiler](https://docs.python.org/3/library/profile.html) we should benchmark performance of both time and memory for large datasets operations 
This is the first step in GSOC18 project [improve Data Retriever efficiency for out-of-memory scale datasets](https://github.com/weecology/retriever/wiki/GSoC-2018-Project-Ideas#improve-data-retriever-efficiency-for-out-of-memory-scale-datasets)

@henrykironde @ethanwhite I'll work on this, do you have some advice?

**Comment by ethanwhite** [comment]
Step one is just getting the retriever fully setup with the tests running successfully locally. I think you've already done a nice job of stating the next big step which is running the profiler and starting to get a feel for where the bottlenecks are. I'd probably do a couple of examples of both large and small datasets to produce benchmarks on both and get a feel for what are large data issues vs. other issues. We probably want to do this for all of the different engines as well since the bottlenecks may very between different database managements systems and flat file formats.

**Comment by adhaamehab** [comment]
@henrykironde  @ethanwhite I made a new repo with the benchmark. Can you give me your feedback? 
https://github.com/adhaamehab/retriever-benchmark

**Comment by henrykironde** [comment]
@adhaamehab the best way is to start by doing some research on stress test for each engine. 
There are many articles and youtube videos that you could start with. use "mysql performance test" or "mysql stress test"

**Comment by ethanwhite** [comment]
Closing since this was primarily a discussion issue related to GSOC.
