### ISSUE TITLE
Improve efficiency of CSV installs using SQLite strategy

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1208]
For the SQLite engine we read and right in chunks when possible. This makes large installs like `breed-bird-survey` really quick. The CSV engine is currently much slower (~15x) and I'm wondering if we might be able to use a similar strategy to the SQLite engine to get some big speed ups.

**Comment by coolalexzb** [comment]
Hello, I have a question about this issue. When installing datasets by sqlite, it improves its efficiency by the use of `cursor.executemany`. When installing datasets by csv, it writes to a .csv file by `executemany` function in csvengine.py. In` executemany` function, when I print the value of statement or values(these two variable have the same value using csv engine), data is also divided in chunk and it only takes several times to write to a file. I think it makes use of a similar strategy with sqlite already. Is the result of a slower speed in csv caused by writing to a file directly rather than using database? @ethanwhite @henrykironde

**Comment by henrykironde** [comment]
In the CSV engine, `executemany` still reads line by line and tries to write several of these. It is like `writelines` vs write for a single line. 
However, SQL engines can load data into the database without processing line by line. When data is clean we do not need to process the line by line. we need to more less load the whole file to the engine. I think for postgres that function is COPY and for sqlite we perform the same using read chuck as in the ref below
Some ref on sqlite: https://github.com/weecology/retriever/commit/8fff6cddb8253a1f396d1ad492214e478d8b4da3#diff-31ca15953e7058ab0b80525b04a2de29

**Comment by coolalexzb** [comment]
I have improved the speed of large csv installs like ` breed-bird-survey` successfully, while I cannot pass pr test. I feel difficult to understand the error information. It seems a encoding problem. Could you give me some help? Besides, are there some ways to test locally rather than committing several times? The test functions need some data as parameters but it seems that I cannot provide it locally. Thanks! @henrykironde  @ethanwhite

**Comment by coolalexzb** [comment]
I have improved the speed of large csv installs like breed-bird-survey successfully ＃1323, while I cannot pass pr test. I feel difficult to understand the error information. It seems a encoding problem. Could you give me some help? Besides, are there some ways to test locally rather than committing several times? The test functions need some data as parameters but it seems that I cannot provide it locally. Thanks! @henrykironde @ethanwhite

**Comment by coolalexzb** [comment]
I have improved the speed of large csv installs like breed-bird-survey successfully #1323 , while I cannot pass pr test. I feel difficult to understand the error information. It seems a encoding problem. Could you give me some help? Besides, are there some ways to test locally rather than committing several times? The test functions need some data as parameters but it seems that I cannot provide it locally. Thanks! @henrykironde @ethanwhite

**Comment by coolalexzb** [comment]
I have improved the speed of large csv installs like breed-bird-survey successfully #1323 , while I cannot pass the pr tests. I feel it difficult to understand the error information. It seems an encoding problem. Could you give me some help? Besides, are there some ways to test locally rather than committing several times? The test functions need some data as parameters but it seems that I cannot provide it locally. Thanks! @henrykironde @ethanwhite

**Comment by henrykironde** [comment]
Hi @coolalexzb,

>  Besides, are there some ways to test locally rather than committing several times? 

Committing(Pushing) several times is okey, but it is not ideal. Usually you test locally first and then push once your local tests pass.

> The test functions need some data as parameters but it seems that I cannot provide it locally. Thanks!

I am not sure what parameters but I think you are talking about passwords for MySQL and Postgres engines. https://retriever.readthedocs.io/en/latest/developer.html#passwordless-configuration
If the docs can't help we can set up sometime this week to walk you through the setup

>  I feel it difficult to understand the error information

Sometimes it is hard, in this case there is some encoding problem I want to guess. I will got through this before the weekends and I will get back to you.

**Comment by coolalexzb** [comment]
Thanks for your help! Other than the encoding problem, another problem is made by Nan value which I described in #1323 . When you get through the error, I think it also an important part to review. This is a polite reminder. I will try to help solve this problem by myself this week as well. Thank you! @henrykironde

**Comment by coolalexzb** [comment]
Hi, I was trying to set up a developer environment these days to test function locally but I got a problem which might be an encoding problem. I search the error on google but do not find a good solution. Could you give me some advice or provide some configuration information of postgresql in detail? Thanks! @henrykironde 
![2019-05-06 11-07-08屏幕截图](https://user-images.githubusercontent.com/19755247/57205267-ff251d00-6fef-11e9-902e-f3fa616e7939.png)
![2019-05-06 11-08-35屏幕截图](https://user-images.githubusercontent.com/19755247/57205270-064c2b00-6ff0-11e9-827e-7754d7a2eb9a.png)

**Comment by henrykironde** [comment]
Which version of Postgres are you using?

**Comment by coolalexzb** [comment]
postgresql-9.6 & postgis-2.3

**Comment by henrykironde** [comment]
Could you try to install version 10.

**Comment by henrykironde** [comment]
Also, could you try this 
```
apt-get install -y --force-yes postgresql-client
apt-get install -y --force-yes postgis
pip install psycopg2-binary -U
```
Let me know what happens

**Comment by coolalexzb** [comment]
I get a similar error saying that schema "testschema_retriever" does not exist, which is also caused by the encoding problem(`psycopg2.errors.UntranslatableCharacter: character with byte sequence 0xe9 0x94 0x99 in encoding "UTF8" has no equivalent in encoding "LATIN1"`). Other errors are also caused by this reason. Besides, I use the command `apt-get install -y --force-yes postgresql-10` and then postgresql-client and postgis are automatically installed. I create testdb_retriever database in postgresql-server, is that right? 
![2019-05-06 23-43-32屏幕截图](https://user-images.githubusercontent.com/19755247/57237119-19dfac00-7059-11e9-8666-3ca94fa67b9e.png)

**Comment by coolalexzb** [comment]
I get a similar error saying that schema "testschema_retriever" does not exist, which is also caused by the encoding problem(psycopg2.errors.UntranslatableCharacter: character with byte sequence 0xe9 0x94 0x99 in encoding "UTF8" has no equivalent in encoding "LATIN1"). Some errors are also caused by this reason. Some errors are caused by the failed installation of the schema. Besides, I use the command` apt-get install -y --force-yes postgresql-10` and then postgresql-client and postgis are automatically installed. I create testdb_retriever database in postgresql-server, is that right? Thank you!
![2019-05-06 23-43-32屏幕截图](https://user-images.githubusercontent.com/19755247/57237445-d0dc2780-7059-11e9-9d36-a717a031be06.png)
![2019-05-06 23-52-42屏幕截图](https://user-images.githubusercontent.com/19755247/57237750-6aa3d480-705a-11e9-981b-a91f4553f7e3.png)

**Comment by henrykironde** [comment]
Lets try running this command and see

```sql
CREATE DATABASE testdb_retriever
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'English_United States.1252'
       LC_CTYPE = 'English_United States.1252'
       CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE testdb_retriever TO public;
GRANT ALL ON DATABASE testdb_retriever TO postgres;
```

**Comment by henrykironde** [comment]
You can set the local to
windows
```
       LC_COLLATE = 'English_United States.1252'
       LC_CTYPE = 'English_United States.1252'
```

nix

```
en_US.UTF-8
en_US.UTF-8
```

**Comment by henrykironde** [comment]
I think we may be doing this efficiently right now. We can open a new issue in case we need some more twitching on the the engine
