### ISSUE TITLE
[discussion] Retriever Provenance

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1250]
For adding the feature of provenance to retriever I am thinking of creating something like
```python
with dataset('airports', hash='123asd12asdeffbdf') as dataset:
   .
   various computation
   .
```
or
```python
data = dataset('airports', hash='123asd12asdeffbdf')
```
to use a particular version of dataset.

For this, I am thinking of adding the ability to commit datasets.
Various commits of the dataset will be stored in a directory.
![multi](https://user-images.githubusercontent.com/21103831/53316539-5622bd80-38ee-11e9-8398-e5d46b362eb3.png)

The plus point is that we keep retriever backwards compatible with the json scripts so if we have the old data and old version of the script the dataset should be then easily usable.

For committing a dataset I created a function that calculates the md5 of a dataset stored in .retriever/raw_data/ and if that dataset has not already been committed I create a new directory with its name as the md5 and copy all file from raw_data/dataset/ to raw_data/provenance/dataset/md5_hash/

The problem with this approach as already discussed with @henrykironde is that every time a dataset is committed, for every commit it copies all the data. This leads to redundancy of data. For subsequent commits, we should store only the data that has changed. For this, we need to do something like what [git](http://git.github.io/git-reference/) does. 
Since almost everyone has `git` I am now thinking of a design in which we can initialize a git directory for each dataset and switch between commits programmatically using retriever to use different versions of the dataset.

@henrykironde @ethanwhite @zhangcandrew Your thoughts and suggestions on this?

**Comment by ethanwhite** [comment]
Thanks for your interest in this @apoorvaeternity. I like the general design, but I'm concerned about committing datasets using git because some of the datasets are too large for git to handle (e.g., vertnet). One of our goals is to help support out-of-memory scale data and that will by definition be too large for git. I think in most cases uses won't regularly be caching a lot of different versions, so in general I think storing full copies of the dataset is OK (though I think @henrykironde's concern about doing this unnecessarily is a good point).

My other thought is that while I initially liked the idea of storing this information in `.retriever`, thinking about it a bit more I'm concerned that as a hidden, local, directory it may not be sufficiently portable for some users. Most users won't back up this directory (I don't) and explaining how to move the cached versions of the data/scripts to another machine will be difficult for less advanced users.

What do you think about storing the information needed to rerun things in the working directory (or some other location specified by the user)? We could have  the user explicitly ask to store an analysis and have the retriever create an archive that contains the script and data. The UI would then be something like:

```
retriever install sqlite my_archived_analysis.tar.gz
```

**Comment by apoorvaeternity** [comment]
@ethanwhite Basically, the issue here is of reproducibility. When someone is doing some research, at a time they are not working with too many versions of a dataset. It would be great if someone can reproduce their scientific work easily even after a long time.
The idea of committing a dataset to a `.tar.gz` file is great. It will make portability of the dataset easier.
What I am thinking is when a user commits a dataset by default we can store the different versions of dataset in .retriever directory and allow something like.

`retriever versions airports`

This will show the different versions of airports dataset present with some metadata like its hash value and the time and date the dataset was committed.

We can also allow committing of datasets in custom directories:
`retriever commit airports --path /home/apoorva/Desktop/ --name airports  --hash HASH`(if a commit with that hash is already present in .retriever folder)
and this will create a zip file for the airports dataset.

Then for installation:
`retriever install sqlite /home/apoorva/Desktop/airports.tar.gz`

And you are right, git is great for small files but not for large files so it will create issues with large datasets and even if we are considering small datasets it won't be very portable.
The issue of same copies of dataset is still there but if we want portability of data I think we need to have full copies.

Your views on this?

**Comment by zhangcandrew** [comment]
If you're set on keeping around different versions of the dataset, it might be cool to look into OrpheusDB for this:
- http://orpheus-db.github.io/index.html
- https://github.com/orpheus-db/implementation

which attempts to solve the problem of versioning for datasets. It is based on MySQL and Python, so I think it could lend itself to retriever well. They have a couple papers on the subject of dataset versioning that might be good to look at.

This might be overkill though if we don't plan on extending our provenance capability, or users don't cache different versions of old datasets regularly, so I think having retriever create some analysis package combo of datasets/script/whatever would be good enough. In this case, we wouldn't be held responsible for keeping different versions of datasets, but only provide users with the ability to create a cached retriever analysis package which can be fed back into retriever.

**Comment by apoorvaeternity** [comment]
@zhangcandrew Thanks for the suggestion. OrpheusDB is surely cool but  IMO  `"some analysis package combo of datasets/script/whatever"` would be more flexible in our case and for the users as well. This will allow users to easily reproduce the results without any external dependency and also allow easy sharing of their own created package with others.

**Comment by ethanwhite** [comment]
Sorry to be slow getting back to you @apoorvaeternity. I really like your current vision for this and think you should go ahead and start developing the proposal. I think that since most datasets won't update that often and most users won't update them repeatedly that keeping full copies (especially compressed) should be fine.

@zhangcandrew - that is a cool tool that I didn't know about before. Thanks for mentioning it. I agree with @apoorvaeternity that keeping things simple for now is the best way to go.

**Comment by apoorvaeternity** [comment]
@ethanwhite Okay, I will start my work on the proposal.

**Comment by ethanwhite** [comment]
Closing since this was a discussion issue for last year's GSOC (which @apoorvaeternity implemented!)
