### ISSUE TITLE
latin-1 -> utf-8 / Python 2.7 support

### ISSUE THREAD

**Issue by scls19fr** [weecology/retriever#1276]
Hello,

Following https://github.com/weecology/retriever/pull/1274#issuecomment-469813400
maybe all scripts encoding should be changed from latin-1 to utf-8.
This is a quite common practice with Python 3.

Maybe this kind of decision should be considered with dropping Python 2.7 support 
https://www.python.org/dev/peps/pep-0373/

> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

Pandas core team dropped support for Python 2 since 1st January, 2019.

https://www.analyticsvidhya.com/blog/2018/04/pandas-will-drop-all-support-for-python-2-next-year/

And retriever is using Pandas...

Kind regards 

Related #716

**Comment by scls19fr** [comment]
http://pandas.pydata.org/pandas-docs/version/0.24.1/whatsnew/v0.24.1.html

> Warning The 0.24.x series of releases will be the last to support Python 2. Future feature releases will support Python 3 only. See [Plan for dropping Python 2.7](http://pandas.pydata.org/pandas-docs/version/0.24.1/install.html#install-dropping-27) for more.

**Comment by henrykironde** [comment]
Thanks @scls19fr, this is one great feature that I totally support and can't wait to drop 2.7.

However, on the other side, we have folks who are still in the middle of writing their research and are using the old versions of the retriever which do not have panda. We do not want to have these folks traumatized, I know how terrible it is to wake up one day and your whole pipeline is failing because some tool was updated without backward compatibility or even informing you earlier.

**Comment by hugovk** [comment]
An good tip for ensuring whole pipelines don't fall apart, is to include an argument like this in the call to `setup()` in `setup.py`:

```python
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*,
```

This ensures that pip only installs the right version of a package for the user's running Python version. In this example, 2.7 and 3.3+ are supported.

When dropping Python 2, use something like this for 3.3+:

```python
python_requires='>=3.3,
```
