### ISSUE TITLE
reset_script does not seem work well

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1302]
Add test for reset_retriever. 
The test case should be something like.

```python
# test for reset all
import retriever as rt
rt.reset_retriever() 
# assert test
rt..dataset_names() == []
```
```python
# test for reset a given script
import retriever as rt
rt.reset_retriever("iris") 
# assert test
"iris" not rt.dataset_names()
```

**Comment by harshitbansal05** [comment]
@henrykironde I think that the test condition would not be appropriate, as "iris" would still be present in `rt.dataset_names()` even after running `rt.reset_retriever("iris")`, due to its presence in the scripts folder of the retriever repository. It would pass when run from any other place besides the local git repo. Please correct me if I am wrong.

**Comment by henrykironde** [comment]
We can actually test them using `reload_scripts()`
```python
# test for reset a given script
import retriever as rt
rt.reset_retriever("iris") 
# assert test
rt.reload_scripts()
"iris" not rt.dataset_names()
```

In the reset_retriever function, we could call reload_scripts at the end to update the script list.
In case there are cyclic dependencies. we can re-organize those functions.

**Comment by henrykironde** [comment]
update:
```python
# test for reset a given script
import retriever as rt
pwd_name = os.getwd()
workdir = tmpdir.mkdtemp()
workdir.chdir()
rt.reset_retriever("iris") 
# assert test
rt.reload_scripts()
"iris" not rt.dataset_names()
# os.chdir(retriever_root_dir)
os.chdir(pwd_name)
```
