### ISSUE TITLE
breed-bird-survey broken due to change by data source

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1372]
Looks like BBS did it's annual update and we're broken again:

```
(base) ethan@oneesk:~$ retriever install sqlite breed-bird-survey
=> Installing breed-bird-survey

Saving a copy of SpeciesList.txt...
Downloading SpeciesList.txt: 280kB [00:01, 159kB/s]                                                                                                                                                                
'utf-8' codec can't decode byte 0xe0 in position 1565: invalid continuation byte
Done!
```

**Comment by ssnell6** [comment]
Ethan, I was using the rdataretriever dataset to access the bbs (counts dataset specifically, 2001-2015) and the rpid column seems to have been added in, duplicating some routes in my dataset. Now I have to have a line filtering out certain rpid codes to remove duplicates.  I was using the same code before this with no duplicates, is it possible these settings also changed with this update?

**Comment by henrykironde** [comment]
Hi Sara, sorry for the delay on this. I am getting it fixed right away. Since the folks from bbs change the data annually, It may be hard to get your analysis looking exactly the same. 

`The good news is that we have added a new feature, Provenance, to the current master that enables you to commit and archive datasets and installation of the committed dataset at a later date. This ensures that the previous outputs/results can be produced easily` 
**Provenance:** https://retriever.readthedocs.io/en/latest/provenance.html

**Comment by ssnell6** [comment]
thanks so much, this is really helpful!

**Comment by henrykironde** [comment]
@ssnell6 I think I got breed-bird-survey(BBS) to work locally, I will put in the changes in the evening.
The new version of BBS has some changes with the encoding which we will need to handle and a few file changes that are not mentioned in the `whatsnew.txt`
After which, we shall be good to run BBS.

ref: ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/

**Comment by henrykironde** [comment]
@ssnell6, What operating system are you using?

**Comment by ssnell6** [comment]
windows

**Comment by ethanwhite** [comment]
@ssnell6 - @henrykironde just put in a fix. To see if it works for you can you please run:

```
retriever reset all
retriever update
```

And then reinstall BBS and let us know how things look.

**Comment by ssnell6** [comment]
Thanks Ethan and Henry, I’m good to go now!
