### ISSUE TITLE
Issues in PR 1374

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1378]
@harshitbansal05 and @apoorvaeternity we can paste all the issues here and test command that have worked fine #1374 

- [x] 1. retriever-recipes edit-json abalone-age (and  delete_json)
- [x] 2. Print statement after `retriever ls` results needs a change on how it displays

**Comment by zhangcandrew** [comment]
This was a minor issue but it seems like in the retriever-recipes-dev branch, retriever ls will sometimes show duplicates after a script has been reset. 

![image](https://user-images.githubusercontent.com/15080652/63481546-ba6ca700-c463-11e9-8174-eede8f10f57b.png)

I imagine it's because we're looking for the existence of a script in multiple areas but this shouldn't be a big deal. If we put the list of scripts in a set before showing ls, this should get rid of the problem. 


Otherwise, sometimes doing a retriever ls -k or -l returns (what I think are unexpected results but correct me if I'm wrong). 
![image](https://user-images.githubusercontent.com/15080652/63481659-28b16980-c464-11e9-94b9-b47a00eab12b.png)

It seems like it can pull and show offline/online datasets which is awesome, but sometimes the online datasets seem to get cutoff? Does this have to do with scripts existing both offline and online?

**Comment by harshitbansal05** [comment]
@zhangcandrew thanks for pointing them out. I have solved both the above issues. Also, I have implemented the feature, you pointed out in https://github.com/weecology/retriever/pull/1362?fbclid=IwAR2cF6ARya2JXgNQXIhIg0E2hJBMk9jStxYL4q_yAPHYIpAMhcG9Sj9asts#discussion_r305595368. So, should I now create a new pr for them, or push to the existing one?

**Comment by harshitbansal05** [comment]
Provenance commands tested:
1. `retriever commit iris -m "Test commit" --path "./"`
2. `retriever install csv iris-7358ae.zip`
3. `retriever commit iris -m "Test commit"`
4. `retriever log iris`
5. `retriever install sqlite iris --hash 7358ae`

All the above commands worked fine and as expected for me.  Great work @apoorvaeternity.

@zhangcandrew @henrykironde ^.

**Comment by zhangcandrew** [comment]
This is really cool! I was playing around with the new commands, all of them seemed to be working as well as normal retriever functions. This is really going to be awesome going in. 

@apoorvaeternity, while I was playing around, I noticed that commits don't seem to show up when I use the path flag in the logs: 

![image](https://user-images.githubusercontent.com/15080652/63559814-7344eb80-c521-11e9-81dd-ede7f18a24d5.png)


Was this intentional? Or am I using this wrong?

**Comment by apoorvaeternity** [comment]
@zhangcandrew It was intentional. The logs are meant for dataset only in `PROVENACNE_DIR`.

**Comment by apoorvaeternity** [comment]
### Testing `retriever-recipes new_json`
<img width="594" alt="Screenshot 2019-08-24 at 9 02 47 PM" src="https://user-images.githubusercontent.com/21103831/63639779-4de8e680-c6b5-11e9-8cec-bd1feaa9ab74.png">
Why is encoding being asked two times?

### Testing `retriever-recipes edit_json`
<img width="1678" alt="Screenshot 2019-08-24 at 9 20 47 PM" src="https://user-images.githubusercontent.com/21103831/63639787-7670e080-c6b5-11e9-9571-c7c4e6da494f.png">
This command is unable to find the script.


### Testing `retriever-recipes delete_json`
<img width="732" alt="Screenshot 2019-08-24 at 9 25 37 PM" src="https://user-images.githubusercontent.com/21103831/63639803-bcc63f80-c6b5-11e9-8b4e-9d58ec1d0526.png">
<img width="1680" alt="Screenshot 2019-08-24 at 9 30 42 PM" src="https://user-images.githubusercontent.com/21103831/63639858-7f15e680-c6b6-11e9-88d3-220aeda8df59.png">
Shows wrong filename in confirmation and doesn't really delete the script file.
@harshitbansal05 @henrykironde @zhangcandrew 

Are there any more commands that have to be tested?

**Comment by harshitbansal05** [comment]
@apoorvaeternity thanks for pointing out. I found the cause for the `encoding` being asked twice, but I could not reproduce the other two errors. They just worked fine for me. Are you using the latest version?

**Comment by apoorvaeternity** [comment]
Yeah just realised my version was not updated. Testing it out more. Other commands seem to work fine.

**Comment by henrykironde** [comment]
**`retriever ls `** : I do not get to see the red colors and I think it depends on system.
Let us reword the print statements. And we can print 2 lines instead of one really long line
`To see the full list of available online datasets, visit https://github.com/weecology/retriever-recipes.`

<img width="1280" alt="Screen Shot 2019-08-24 at 4 14 25 PM" src="https://user-images.githubusercontent.com/5192965/63642265-ad7dcc80-c68a-11e9-9c20-4f46401b5183.png">

**Comment by ethanwhite** [comment]
@henrykironde is right that color won't be universal. One option is to also display a character to indicate the same information (e.g., an `*`, `+`, or `@`) at the end/beginning of those datasets (e.g., `vertnet*`) so that they're status is visible whether there is color or not.

**Comment by henrykironde** [comment]
fixed in #1381
