### ISSUE TITLE
Add JSON engine

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#152]

**Comment by ghoshbishakh** [comment]
I can see a jsonengine.py and it looks pretty complete. So it this feature already complete or something I can do about it?

**Comment by henrykironde** [comment]
yah it looks complete but there is more to do. you can check the comments in the engine and also refer to this branch
https://github.com/henrykironde/deletedret/tree/JSON-engine in case

the best way to confirm that it works fine is by developing [regression tests](https://github.com/weecology/retriever/blob/master/test/test_regression_cli.py#L120)

some issue to consider:
1) The organization of the data since Json reads objects in a mapped kind of way.
 There is away to keep the order of the data as you write to the json file.

**Comment by ethanwhite** [comment]
This engine has been really close for a while, but there were some edge cases that were causing issues the last time I checked (see #165 for some discussion). It would be great to clear out any remaining bugs and make it available.

I agree with @henrykironde that the starting point here would be to:

- [ ] Activate the engine by adding it to the `engine` list in `engines/__init__.py`
- [ ] Try to do some installs of both single table and multi-table datasets and check to see if they are valid JSON (using something like http://jsonlint.com/)
- [ ] Write regression tests for it.
