### ISSUE TITLE
Cleanup whitespace to conform with PEP8

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#279]
We haven't had a whitespace policy in place in the past, which means there is a lot of fairly variable trailing whitespace throughout the code. This has led to a few PRs with huge diffs because the contributors have their editors set up to cleanup whitespace.

I'm proposing that we do one big whitespace cleanup to remove trailing whitespace from all files and more generally implement PEP8 whitespace rules throughout.

Thoughts @bendmorris?

**Comment by bendmorris** [comment]
I think this is a good idea. Specifically for whitespace on blank lines, PEP8 doesn't set a standard: http://stackoverflow.com/questions/2727988/python-indentation-in-empty-lines

It's basically up to personal preference and there are good arguments for and against, so I'd suggest we decide either to use whitespace on blank lines, or not use it. I'd vote for whichever is most common in the codebase currently.

It would be good practice for contributors to adjust their IDE whitespace settings to conform to whatever the project sets as standard rather than assuming a plugin or IDE feature are automatically correct. If there are irrelevant whitespace changes in a diff, they should be removed prior to merging. I know that's a pain for new contributors, but it's a reality of multiple people working together.

**Comment by akshayah3** [comment]
@ethanwhite I think thats a great idea! I will work on this as I myself who am accustomed to pep8 have found it difficult reading some parts of the code.

**Comment by ethanwhite** [comment]
Fixed by 7e4e2c4a80123b84bd6c15def89cf9a0ae8df5da.
