### ISSUE TITLE
"available datasets" page seems out of date

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#344]
The list at http://www.ecodataretriever.org/available-data.html doesn't seem to include the Portal rodents, for example?

**Comment by ethanwhite** [comment]
The Portal rodents are there, just under the official title of the paper:
Long-term monitoring and experimental manipulation of a Chihuahuan Desert ecosystem

but that page definitely tends to get out of date and probably is missing something else right now. Ultimately it should be autogenerated so that maintaining it is easier.

If you see particular things that need to be added either specific issues or PRs to:
https://github.com/weecology/retriever-website

would be great. Thanks!

**Comment by davharris** [comment]
Ah, okay.  I ctrl-F'd for "portal", "rodents", "mammals", and a few other keywords and came up empty.  Sorry for the mistake.

**Comment by ethanwhite** [comment]
Nothing to apologize for. I think that page would really benefit from a lot of thought to help deal with exactly that sort of confusion. I'd have done the same thing you did to be honest :) It was only because Portal was one of the very first datasets we developed that I knew it had to be there.
