### ISSUE TITLE
Add vertnet data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#357]
http://vertnet.org/resources/datatoolscode.html

**Comment by mbjones** [comment]
@ethanwhite That page directs you to the human-oriented landing page for each of the data sets. Because these data files are in the KNB, you can also get the associated metadata and data files via the DataONE API.  For example, for amphibians, you can download the whole package (both metadata and data files) as a zip file using its package identifier, like so:

- Whole package download: https://knb.ecoinformatics.org/knb/d1/mn/v1/package/urn%3Auuid%3A09501379-a321-47c2-a55b-cce7e8c480a5

Alternatively, you can download just a single data file from the package using the object service endpoint and its identifier, e.g., 

- For the EML document: https://knb.ecoinformatics.org/knb/d1/mn/v1/object/doi:10.5063/F1VX0DF9
- For the data file: https://knb.ecoinformatics.org/knb/d1/mn/v1/object/urn:uuid:afc58110-b9c1-4cf7-b46c-837bdc930a21

There are a number of other REST APIs available as well, such as doing a SOLR query to determine if a newer version of a data package has been created (which will be the case for the VertNet data periodically).

**Comment by ethanwhite** [comment]
Thanks @mbjones! Much appreciated.
