### ISSUE TITLE
Mac: easy_install errors and warnings

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#395]
From the output of `bash build_mac` on my computer:

```
running easy_install
error: No urls, filenames, or requirements specified (see --help)
```

Also:

```
/Users/davidharris/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
/Users/davidharris/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zipfile'
  warnings.warn(msg)
```

I don't think any of these are hurting anything, but it's hard for me to tell for sure.  The warnings about unknown distribution options seem to relate to Windows-only commands getting included in the Mac script.

**Comment by ethanwhite** [comment]
The first one is weird. I don't know of anything in there that should trigger running `easy_install` (which no one even uses any more I don't think. Can you tell which line is triggering it?

The other two can be ignored. They show up because their is a single `setup.py` file regardless of the OS. There may be a way to clean those up, but let's split that out into a separate issue.

**Comment by ethanwhite** [comment]
Closing since we can't replicate the first output and the warnings can be ignored.
