### ISSUE TITLE
Adding py3 support to lib/engine.py fails on py.test

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#452]
Hi @henrykironde @ethanwhite 
 
In the recent test suite change to py.test, these changes on my branch fail the Travis-CI tests:
[commit](https://github.com/goelakash/retriever/commit/001fc070affe140e741fa8342b758821a86c51ea)

This is the build log: [log](https://travis-ci.org/goelakash/retriever/builds/119124990)

Any idea why the assertion errors are coming up?

**Comment by henrykironde** [comment]
Hi @goelakash sorry for the late reply,
I have gone through the log and there is no red flag.
However this is the catch, the pytest version does not report all the log details because it is silent(configurations). So basically, Travis is for a final confirmation on the tests.

I suggest, running the tests on your own machine.
Either you can use nosetests or  py.test in the main directory 
`path_retriever_home_dir$ nosetests`
`path_retriever_home_dir$ py.test`
and also run `python setup.py install` to first install it on the system before any tests I do not recommend running `Python setup.py develop` 

**note:** for any changes in the code i always recommend running `python setup.py install`

On my side, all the tests failed and the scripts can not load.
if you don't have all the version of database systems to test you could do it in a hacky way :)
by commenting out tests on some engines in test/test_regression_cli.py

Feel free to drop any questions any time
