### ISSUE TITLE
Transition to Python 3 and change scripts format to JSON

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#487]
References: #167 and #326 

The current list of objectives includes:

- [x] Update .script to .json files
- [x] Update code for Python2/3 compatibility
- [x] add CLI options for creating a metadata .json file for a new dataset, and edit old ones.

__Start date - 23rd may__

Week 1
---------
Convert .script files to json

Week 2
---------
Add JSON compilation support.

Week 3 & 4
--------------
Start developing the CLI tool. 

Week 5 & 6
--------------
Work on adding Python 3 support

Midterm evaluation Deliverables
-----------------------------------------
 - datapackage.json scripts
 - CLI tool for datapackage.json metadata file creation
 - Python 3 support

Week 6 & 7
--------------
Writing tests for the test-suite and improve test-suite coverage

Week 8
---------
Triaging bugs and problems associated to consolidation of cross-tabulated data.

Week 9
---------
Writing documentation

Final evaluation Deliverables
------------------------------------
- Additional tests
- Documentation for datapackage.json CLI and manual editing
- bug-patches

Post- GSoC
---------------
Add new features and work on other bugs and issues.

**Comment by ethanwhite** [comment]
@henrykironde & @goelakash - this is a great super issue for covering all of the things that @goelakash is working on this summer as part of GSoC. @goelakash - I'm guessing that @henrykironde's already talked with you a bit about the ideas behind these sorts of issues, but in the spirit of GSoC giving you exposure to who folks work on bigger projects I thought I'd take a couple of minutes to give my thinking behind this sort of thing and then make a suggestion or two for making this one even better.

When working on major changes like the two sets of things you're working on this summer it's important to keep track of all of the different bits and pieces to make sure that everything gets done and that you're managing your time well (e.g., not spending most of your time on a small piece of the project and not getting around to the more core elements). There are two general approaches to this that we use in our work: super issues and milestones.

Super issues, like this one, collect all of the different pieces of the bigger task together in a single issue. You can use the `- [ ] item 1` and `- [x] item 2` markdown notation to produce lists like:

- [ ] item 1
- [x] item 2

that let you check off items right in the issue. Each item is then often associated with a smaller sub-issue where ideas/discussion/tracking of that specific task can happen. These sub-issues are often associated with the items, e.g., 

- [ ] item 1 #22 
- [x] item 2 #26 

The super issues allow discussion and improvement of the big picture plan, while the sub issues allow the details of any particular task to be recorded and discussed. The super issues can and should be continually edited if ideas change about what needs to be done so that the top of the issue is always the place you go first to understand what's supposed to happen next.

Another option is to use milestones. We use these for thinking about and prioritizing what should go into releases (e.g., https://github.com/weecology/retriever/milestones), but they can also be used for tracking bigger features with lots of smaller changes to me made. To do this each issue that is associated with part of a bigger task has the milestone for that task added to it. You can then look at the page for that milestone (e.g., https://github.com/weecology/retriever/milestones/2.0) to see what is left to be completed, how much work you've already done, etc.

The one thing I'd say about this current super issue is that I tend to think of these as applying to a feature rather than to a person. These tend to blend together a bit in GSoC, but since @goelakash's proposal actually has a couple of components I think we can separate them more than usual. So, my suggestion for this current super issue is that @goelakash split it into separate super issues, one for adding Python 2/3 compatibility and one for transitioning JSON data standard. Then also create sub issues for the individual pieces of each bigger task. These can include any thoughts you have about how you're going to make those changes. Then link to the sub-issues in the super issue.

If you (@goelakash) think it would be useful you could also use milestones to help with time management by adding midterm and final evaluation milestones and associating individual issues with those milestones.

Hopefully this gives you some useful perspective on our approaches to managing larger changes. Let me know if you have any questions.

**Comment by goelakash** [comment]
Python 3 compatibility list (remaining issues):

- [ ] future builtins
- [ ] Newstyle classes

**Comment by henrykironde** [comment]
@goelakash, from the latest updates, it looks like most of the parts are up and working and a some debugging. 
So could we go ahead and edit the commits, do some refactoring and add some tests.

 We shall also add documentation for all the new updates. Both at the developer side and user side.
For example `how to change from .script to .json`.  (This can come in later)

If we compare this branch with the master branch, 
we could categorize the commits as below:

```
update the version file for the json upgrade
update test files to use json scripts
convert .scripts to .json (or add json files)
add parse_script_to_json module. 
add datapackage python module
Add CLI to create datapackage.json
```
These are just examples and you could come up with better fitting descriptions.

**Refactoring :** 
I understand refactoring is on your list but I am just making some more notes here

- comments:
I like the inline comments, however some comment are too long
```
        if len(values) == 1:                   
            table['dialect'][key] = values[0]           # not a list type for a single value (bool,int, etc)
```
may be putting them just above would be good as below

```
                            if len(values) == 1:
                                # not a list type for a single value (bool,int, etc)
                                table['dialect'][key] = values[0
```

space after hash (#comment) --> (# comment)

Functions are too long, is there anyway we could come up with some refactoring in some of those function definitions?

**Adding doc strings:** 
Initially we have not been adding much description in the doc strings. For these sets of features and functions, we should add as much doc strings and descriptions as possible. A good example by Ethan is [here](https://github.com/weecology/retriever/blob/8f67c16a47ffa41a5d424723d4360394eee17cfc/lib/engine.py#L531)


**What is not working:**
Currently we are converting from json to python. which is really nice.
Please check that the compiled versions are the same as the previous version. If they are different,  make sure that the difference is accounted for. For example, in delmoral we have': `Table('species', escape_single_quotes=True,do_not_bulk_insert=True)}`
in the old version we have 
`Table('species', escape_single_quotes='True',do_not_bulk_insert='True')}`,

Try to test with some of the notorious datasets we have like:

 ```
Delmoral2010 , Getry, steppe_plants_2013
BBS, SonoranPerennials, GWDD,  palmer2007, Woods2009, ramesh2010, Steppe_plants_2013, delmoral2010
```

Note: cleaning up the commits can be done on another branch. I know we need the commit history for the Google summer final evaluation and report, we can keep those commits on a different branch.

**Comment by goelakash** [comment]
@henrykironde Thanks for the feedback. I'll keep these in mind and do the changes so that compiled scripts are as identical to the old one as possible. 
For the squashing of commits, I think that I should fork the `scripts-to-json` branch and then add a PR to `master` for review. What do you think?

**Comment by henrykironde** [comment]
`so that compiled scripts are as identical to the old one as possible.` They do not have to be identical. It all depends on your design. I just noted that because as I downloaded delmoral, I got into some problems. I looked at the files and found that the `Table` values where a little bit different.   

About adding a `PR` to `Master` after the clean up, sounds Good.

**Comment by henrykironde** [comment]
@goelakash do we need pyyaml?

**Comment by goelakash** [comment]
`json` adds `u` prefixes to strings when read with `json.load()`. I used `pyyaml` to avoid that.

**Comment by goelakash** [comment]
`json` prefixes `u` in front of all the strings when saving to file, which
`pyyaml` leaves out when loading the file.

**Comment by goelakash** [comment]
@henrykironde I think that changing from `True` to `'True'` wouldn't be valid in the `.py` script files, as we also don't convert integers to string type (e.g, we use  `50`, not `'50'`).

**Comment by henrykironde** [comment]
@goelakash, correct and I totally agree with you `Table('species', escape_single_quotes=True,do_not_bulk_insert=True)}` . I guess in the current master version we may be testing that as a string 'True' and not a `.py` key word. 

I was mentioning this so that there is consistency in processing the file. Just like a note.  I didn't get time to check what was causing the errors but I noticed a change in both current master `.py` files and the script branch `.py` files.

**Comment by henrykironde** [comment]
@ethanwhite, and @goelakash,  after a long summer of code, we are almost coming to the end with some good updates on the retriever, ref: [data package branch](https://github.com/weecology/retriever/tree/data-package). Thanks to the hard work from @goelakash, not forgetting all other summer contributors, @Deborah-Digges, @ghoshbishakh, @QuLogic.

Please feel free to add comments or suggestions.

There are a few things that need to be updated, like the introduction page [README.md](https://github.com/weecology/retriever/blob/data-package/README.md)

@goelakash, I think we do not need to make `Site/Homepage of dataset:` mandatory, neither  Description or Citation.  

Also in cases when we don't have enough information to make the script, we should report to the user that there is not enough info. for example when there is no single table added

**Example of script created and tested**

`retriever new_json`
```
Shortname (Give a unique identifier for script): ffff
Title/Name: henry
Description: testing 123
Citation: retriever test
Site/Homepage of dataset: 
	Error: empty input. Need one or more values.

Site/Homepage of dataset: www.google.com
Tags (separated by ';'): 

Add Table? (y/N): y
Table name: test123
Table URL: file:///Users/henrykironde/Documents/test.csv
replace_columns (separated by ';', with comma-separated values) (press return to skip): 
nulls (separated by ';') (press return to skip): 
delimiter (press return to skip): 
do_not_bulk_insert (bool = True/False) (press return to skip): True
contains_pk (bool = True/False) (press return to skip): 
escape_single_quotes (bool = True/False) (press return to skip): 
escape_double_quotes (bool = True/False) (press return to skip): 
fixed_width (bool = True/False) (press return to skip): 
header_rows (int) (press return to skip): 
Enter columns [format = name, type, (optional) size] (press return to skip):

```

**Comment by goelakash** [comment]
@henrykironde I think we should split the last objective to edit scripts through CLI as a separate one, as it is still in progress.

**Comment by henrykironde** [comment]
I don't get it quiet well,

**Comment by goelakash** [comment]
The feature to edit JSON files is disabled. That means that the 3rd objective is only partially completed.

**Comment by henrykironde** [comment]
@goelakash could we include json test in the integration test

**Comment by henrykironde** [comment]
Since we shall get rid of `parse_script_to_json` later, I wanted us to have  something like 
```
jsonsimple_csv = {'name': 'jsonsimple_csv',
                  'raw_data': "a,b,c\n1,2,3\n4,5,6\n",
                  'expect_out': 'a,b,c\n1,2,3\n4,5,6\n',
                  'script': """{
                    "name": "jsoncsv",
                    "resources": [
                        {
                            "dialect": {},
                            "name": "json_csv",
                            "schema": {},
                            "url": "http://example.com/jsoncsv.txt"
                        }
                    ],
                    "urls": {
                        "json_csv": "http://example.com/jsoncsv.txt"
                    }
                }
                """}
```

but I think i will change that later on.

**Comment by goelakash** [comment]
@henrykironde and @ethanwhite I think this super-issue can be closed now.

**Comment by ethanwhite** [comment]
:+1: Thanks!
