### ISSUE TITLE
Obsolete links for some tables

### ISSUE THREAD

**Issue by Deborah-Digges** [weecology/retriever#513]
While testing [this issue](https://github.com/weecology/retriever/issues/290), I used the following command:
```
retriever install postgres eBirdOD
```

However, it seems like the url for this table is no longer valid:
https://dataone.ornith.cornell.edu/metacat/d1/mn/v1/object/CLOEODDATA.05192014.1

and gives me the following  message:
```
Downloading /Users/ddigges/.retriever/raw_data/eBirdOD/CLOEODDATA.05192014.1...from: https://dataone.ornith.cornell.edu/metacat/d1/mn/v1/object/CLOEODDATA.05192014.1
[Errno socket error] [Errno 8] nodename nor servname provided, or not known
```

We should look into any tables that have obsolete links and remove them.

**Comment by ethanwhite** [comment]
Thanks for reporting this @Deborah-Digges. A fresh search on DataONE gives the following (also dead) link:

https://cn.dataone.org/cn/v2/resolve/CLOEODDATA.05192014.1

I've emailed one of the folks I know associated with DataONE to figure out how to report this.

More generally, I totally agree that we need to try to keep track of dead links and other script breaking changes to data. Something that's on the To Do list is building a system that attempts to install all of the associated datasets roughly once a week and reports back on any failures.

**Comment by henrykironde** [comment]
Thanks @Deborah-Digges. This is one feature that we should add and since the tests are now better to work with, we could go ahead and create this test. We could reference the design of [try_install_all](https://github.com/weecology/retriever/blob/master/try_install_all.pyhttps://github.com/weecology/retriever/blob/master/try_install_all.py). Or even redesign it to take a few arguments.

- we should be able to test if a new database being added can install on all the engines
- if all the URLs are still pointing to the required location, He we follow the same structure as the reference but we do not install or read the url content. We should just test for Error 404s,

This actually is related to issue  #456, #389, #455

As for [eBirdOD](https://github.com/weecology/retriever/blob/master/scripts/eBird_observation.py), they have moved the repository. [Dataone](https://www.dataone.org/) and [vertert](http://vertnet.org/resources/datatoolscode.html) are supposedly providing

**Comment by mbjones** [comment]
Thanks for pointing this out.  DataONE has a replication feature that contributors can (optionally) use to specify that they'd like multiple copies of their data stored around the network, but unfortunately, it appears that eBird didn't use this feature.  We'll work with Cornell on getting the objects restored and hopefully replicated to avoid this issue in the future.

**Comment by goelakash** [comment]
This could be added to the `2.0` milestone.

**Comment by ethanwhite** [comment]
Good suggestion @goelakash. Done.

**Comment by ethanwhite** [comment]
@mbjones - any news on this from the eBird folks?

**Comment by henrykironde** [comment]
Closing after thoroughly investigating.
`try_install_all.py` will take care of this
