### ISSUE TITLE
Change the tags/keywords syntax

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#518]
Currently, keywords are stored as `key > value` strings in the `.script` and `.py` scripts.
I was thinking that we could change it to dicts (`{key:value}`) syntax.

For example, from `AmnioteLH.py`:

`tags=['Taxon > Mammals', 'Data Type > Compilation']`

could be made:

`tags={'Taxon' : 'Mammals', 'Data Type' : 'Compilation']`

@ethanwhite @henrykironde @Deborah-Digges

**Comment by ethanwhite** [comment]
As @goelakash have started talking about in [the chat](https://gitter.im/weecology/retriever?at=575d7f6597e1b2d245e2119f), we may want to rethink how we handle tags in light of our expanding the scope of the kind of data the retriever targets (#432). I've suggested that we consider simply moving to uncategorized tags.

**Comment by henrykironde** [comment]
@ethanwhite considering we are moving towards Data retriever that would be a good change. @goelakash, since we are considering the above as the way forward, I think the dicts ({key:value}) may not apply and if we apply this data structure we have to think about some cases like

`tags=['Taxon > Mammals', 'Data Type > Compilation','Data Type > Taxonomy' ]`

So in such cases, we have to map a key to a list of values, and also consider the usage of the tags in the retriever and how the new data structure would fit in the places where we are using the tags variables.

**Comment by ethanwhite** [comment]
What did we end up doing with this and should this issue be closed now?

**Comment by goelakash** [comment]
@ethanwhite We ended up not making any changes to existing syntax.

**Comment by ethanwhite** [comment]
OK, thanks. I think there are definitely improvements to be made here and I like your original suggestion. The biggest question is in my mind is whether we want to maintain any soft of structure to this tagging at all. If we do then your original suggestion looks good to me and it should handle the lists of values issue that @henrykironde mentioned using something like:

```
tags={'Taxon' : 'Mammals', 'Data Type' : ['Compilation', 'Time Series']}
```

The alternative approach would just be to focus on free tagging instead of the category based approach we've taken. It fits nicely in the datapackage spec which contains the [`keywords` field](http://specs.frictionlessdata.io/data-packages/#recommended-fields). In which case we'd just do something like:

```
keywords=['Mammals', 'Compilation', 'Time Series']
```

My initial reaction is to to that route since it fits the spec and applies most generally across disciplines, but I'm certainly open to arguments to keeping more structure. Either way I think this would be a great modular project for someone to tackle at some point.

**Comment by goelakash** [comment]
@ethanwhite I think we should follow the datapackage.JSON standard, since we do not use the classes for any segregation between the tags currently.

**Comment by ethanwhite** [comment]
@goelakash I agree. Let's go ahead and plan on moving to the `keywords` example above. This will take a little more work to change, but I think sticking with the spec is the right approach.

If anyone wants to tackle this they can just assign themselves to the issue to let everyone else know they are working on.
