### ISSUE TITLE
Update Developer Docs for MySQL Installation

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#628]
**
For MySQL installation, while going through the inital setup and installation process, it is important to let the user know that access and file privileges must be granted to travis on their new database testdb on the localhost.

If this is not addressed, the following error will occur:

Couldn't create database ((1045, "28000Access denied for user 'root'@'localhost' (using password: YES)")). Trying to continue anyway.
Creating table BBS.species...
Couldn't create table ((1045, "28000Access denied for user 'root'@'localhost' (using password: YES)")). Trying to continue anyway.
(1045, "28000Access denied for user 'root'@'localhost' (using password: YES)")

**

**Comment by ethanwhite** [comment]
Some of this information is currently in the [Continuous Intregration section of the docs](https://retriever.readthedocs.io/en/latest/developer.html#services-used). I agree that it would be better to move it up under [Testing](https://retriever.readthedocs.io/en/latest/developer.html#testing) since it really applies to local testing instead of CI. Would you like to try a PR moving that docs section up?

**Comment by zhangcandrew** [comment]
Sure! I was going solely off the readMe in the retriever gitHub Repository initially, and only found out about the travis mySQL grants through talking to Henry. Just wondering though, what does PR stand for?

**Comment by henrykironde** [comment]
:) PR is a Pull request. I was confused the first time I heard it.  you can call me to go through the workflow of that.

**Comment by ethanwhite** [comment]
This was fixed in 0190f7824f4769d893134ca95b2cae8080a491a1. Thanks @zhangcandrew!
