### ISSUE TITLE
Postgres testing config instructions produce error on Ubuntu

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#666]
The first line of the postgres testing configuration instructions state that the user should run:
`psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"`

On a clean postgres install on Ubuntu 16.04 this produces an error since the user exists by default:

```
ethan@gandalf:~$ psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"
ERROR:  role "postgres" already exists
```

I wonder if we should instruct the user open postgres and create the password using `\password` instead.

**Comment by ethanwhite** [comment]
@zhangcandrew if you have a few minutes to take a look at this that would be great. Thanks.

**Comment by zhangcandrew** [comment]
I think it'd be best if we kept the psql commands just to ensure that the entire setup is consistent and users can build everything up using just line commands to the CLI instead of logging into psql, changing the password, and logging back out. 

On my computer I can pass the command: 

psql -c "ALTER USER postgres PASSWORD 'testpass';"

and that seems to achieve the same effect. I'm not 100% certain though that it works for a fresh installation, so I was going to set up a virtual machine and test it again. I will keep you updated.

**Comment by ethanwhite** [comment]
Thanks @zhangcandrew! I think you're right that using `ALTER` should solve the problem, but definitely worth checking to make sure.

**Comment by zhangcandrew** [comment]
It seems like the commands 

```
psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"
psql -c 'CREATE DATABASE testdb'
psql -c 'GRANT ALL PRIVILEGES ON DATABASE testdb to postgres'
```

are all invalid on a new installation of ubuntu with a freshly installed postgresql. I ran into the error: 

```
psql: FATAL: role "USERNAME" does not exist
```
whenever I tried to run those commands. I was only able to run the commands when I added sudo -u postgres to the beginning of the commands. Otherwise, using alter user works fine. The final changed commands would look like this: 
```
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'testpass'"
sudo -u postgres psql -c "CREATE DATABASE testdb"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb to postgres"
```

**Comment by zhangcandrew** [comment]
Accidentally closed the issue, my bad.

**Comment by henrykironde** [comment]
how about` sudo psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"`

**Comment by ethanwhite** [comment]
@henrykironde's suggestion should work for me.

**Comment by zhangcandrew** [comment]
When I run
```
sudo psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"
```
I get
```
psql: FATAL: role "root" does not exist
```

It seems like since the default user that comes with postgresql is postgres, we have to explicitly use it in the commands. 

Running 
```
sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'testpass'"
```
also returns the error: 
```
ERROR: role "postgres" already exists
```

**Comment by henrykironde** [comment]
Closing this issue. I have installed Postgres several times and I didn't have this issue. Any one experience this at any time, please feel free to reopen the issue.
