### ISSUE TITLE
Question about Python and Julia Interfaces for the Data Retriever.

### ISSUE THREAD

**Issue by Parth-25m** [weecology/retriever#801]
@ethanwhite @henrykironde 
What do you mean by adding native Python Interface? Does it mean implementing GUI for retriever?
Also what is wrapping CLI in Julia ? Is it making Julia as frontend and python as backend?

**Comment by ethanwhite** [comment]
@Parth-25m Right now the package has a command line interface, but no proper interface in Python and nothing in Julia.

This would create a Python interface so that you could run everything directly from inside Python programs, e.g.,

```
import retriever

# Install Iris data into an SQLite database
retriever.install('iris', 'sqlite')

# Download and load the Iris data into Python
iris_data = retriever.fetch('iris')

# Update the datasets
retriever.update()
```

The Julia part is basically to create a Julia frontend for the Python backend, yes. So basically just an equivalent to the [existing R package](https://github.com/ropensci/rdataretriever).

Does that help clarify things?

**Comment by Parth-25m** [comment]
Yes, thanks for the answer.

**Comment by ethanwhite** [comment]
Closing since this seems to be all settled, but feel free to reopen if you have any more questions.
