### ISSUE TITLE
Test coverage broken

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#842]
Our test coverage is currently reporting 0%. This happened when we moved to the standard Python package structure in 29e5585c5f22df22bdbf5679ff5e422b347fe552. Instead of checking the installed package like it was before:

```
----------- coverage: platform linux, python 3.6.0-final-0 -----------
Name                                                                                       Stmts   Miss  Cover
--------------------------------------------------------------------------------------------------------------
/home/ethan/miniconda3/lib/python3.6/site-packages/retriever/__init__.py                     106     27    75%
/home/ethan/miniconda3/lib/python3.6/site-packages/retriever/__main__.py                     139     90    35%
```

It now appears to be checking the files in the package directory of the same name:

```
----------- coverage: platform linux, python 3.6.0-final-0 -----------
Name                                    Stmts   Miss  Cover
-----------------------------------------------------------
retriever/__init__.py                     106    106     0%
retriever/__main__.py                     139    139     0%
```

Presumably we just need to change the details of `py.test` line in `.travis.yml`.

**Comment by kapilkd13** [comment]
Hi @ethanwhite Can I work on this issue. If yes can you tell me how to obtain the coverage report mentioned above.

**Comment by henrykironde** [comment]
@kapilkd13, the coverage is given by a service called codecov.https://codecov.io/github/weecology/retriever?branch=master
And we are passing the command in `.travis.yml` 

Right now it reports 0%.  since we changed our directory structure,  I think we need to change the path of the tool.
https://github.com/weecology/retriever/blob/master/.travis.yml#L26

We have 

```
script:
  - py.test -v --cov=retriever
```

but I think we should be having 

```
script:
  - py.test -v --cov=retriever/retriever
```
or 
```
script:
  - py.test -v --cov=retriever/retriever
```
most likely

```
script:
  - py.test -v --cov=./
```

Best place to begin is to search on Github for `py.test -v --cov` and try to see the way other python projects have set that value. Also read the codecov docs to see if there is a mention of that.

**Comment by henrykironde** [comment]
@kapilkd13, thank you for the interests in solving this, I think we have found the error and I am putting in a pull request. Apparently we had to install using editable mode `pip install -e .` for coverage tests to work.

**Comment by kapilkd13** [comment]
@henrykironde Great. It was a imp issue. I will look for some other significant issue. O can you suggest a issue that would help me with "Python and Julia Interface for retriever" Project. Thanks.
