### ISSUE TITLE
`edit_json` not working for files with `_` in their names

### ISSUE THREAD

**Issue by kapilkd13** [weecology/retriever#847]
`edit_json`  does not work properly with files having `_` in their name. This is due to the fact that script names and script.name can be different for a json file.

**Comment by kapilkd13** [comment]
Hi, I am working on this. Thanks

**Comment by jainamritanshu** [comment]
@henrykironde @ethanwhite I guess this issue would be solved by #822 since this problem is probably due to internal naming of variables which is being solved in the pull request mentioned above.

**Comment by henrykironde** [comment]
Could you test 822 it and confirm please.

**Comment by jainamritanshu** [comment]
Sorry @henrykironde my bad. I guess the problem was [here](https://github.com/weecology/retriever/blob/master/retriever/lib/datapackage.py#L414) as while saving the file again it saves the file name as the title of the dataset which has '-' for separation. The problem could be solved by changing it.

**Comment by zhangcandrew** [comment]
I believe this is fixed, so I'll close this for now.
