### ISSUE TITLE
Move From Ecological Archives to Figshare 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#862]
Due to the new update in the organization of Ecological Archives, The datasets, and papers are now hosted on two servers ; the old Ecological archieves server`(unstable)` and on Figshare`(stable)`. 

We have a task of moving the script's urls,(`homepage, and the URL links to the actual datasets, and changing filenames in some cases`).

To Solve this issue, I recommend searching Figshare  using citation in the scripts.
The citation will have to change, I this case since the datasets are not changing(tables). So we change the middle number 
Eg. `1.1.1 `becomes `1.2.0`

**Comment by zhangcandrew** [comment]
I can work on this, but just to make sure, are we changing all ecological archive script URLS to their Figshare counterparts?

**Comment by ethanwhite** [comment]
The ESA site has now been down for almost a full week and after several email exchanges with staff there I am not convinced this is going to be addressed any time soon. As a result I'd like to prioritize getting these links updated since it means a substantial fraction of our datasets are currently broken.

Here is the full list of datasets (23 of them) we need to deal with (based on a quick grep):

- [ ] scripts/amniote_life_hist.json
- [ ] scripts/antarctic_breed_bird.json
- [ ] scripts/biomass_allometry_db.py
- [ ] scripts/butterfly_population_network.json
- [ ] scripts/elton_traits.json
- [ ] scripts/fish_parasite_hosts.json
- [ ] scripts/forest_biomass_china.json
- [ ] scripts/forest_plots_wghats.json
- [ ] scripts/fray_jorge_ecology.json
- [ ] scripts/la_selva_trees.py
- [ ] scripts/mammal_life_hist.json
- [ ] scripts/mapped_plant_quads_co.json
- [ ] scripts/mapped_plant_quads_id.json
- [ ] scripts/mapped_plant_quads_ks.json
- [ ] scripts/mapped_plant_quads_mt.json
- [ ] scripts/pantheria.json
- [ ] scripts/phytoplankton_size.json
- [ ] scripts/plant_comp_ok.json
- [ ] scripts/plant_occur_oosting.json
- [ ] scripts/portal-dev.json
- [ ] scripts/portal.json
- [ ] scripts/tree_demog_wghats.json
- [ ] scripts/veg_plots_sdl.json

I don't think we need to wait on one giant PR, so if folks want to start fixing a few of these at a time that would be great. Leave a note in this issue or in the chat if you're about to start (or have already started) working on one or more of these datasets so that we reduce duplicate effort.

**Comment by ethanwhite** [comment]
I'm going to work on the two `.py` scripts now.

**Comment by henrykironde** [comment]
That is very true. Please make sure you only create one PR for each script. Testing these scripts will be very delicate.

**Comment by ethanwhite** [comment]
Let's check things off of the list in this issue once PRs are submitted since the goal here is to coordinate the work and once a PR is in we don't want folks starting a new one.

**Comment by ethanwhite** [comment]
I just put in PRs for `la-selva-trees` and `biomass-allometry-db`. Apologies if whoever check marked those was already working on it.

**Comment by henrykironde** [comment]
One question; the citations of ESA differ from those on Figshare.
Do we change the original citation?

**Comment by ethanwhite** [comment]
We should keep the original citations because those citations actually still stand. For example here's the `la-selva-trees` page:

http://onlinelibrary.wiley.com/doi/10.1890/0012-9658(2006)87%5B2132:TGMPCA%5D2.0.CO;2/full

**Comment by henrykironde** [comment]
Note: `amniote_life_hist.json` and `forest_plots_wghats.json` need to be converted to python scripts.
The data was zip to a single file

**Comment by zhangcandrew** [comment]
I just wanted to add that in addition to what henry put, the following json files were also saved in .zip files on figshare, so they need to be converted to a .py file:

`pantheria.json`
`tree_deomg_wghats.json`

**Comment by zhangcandrew** [comment]
I just put a PR up for the following scripts: 

`scripts/mapped_plant_quads_co.json`
 `scripts/mapped_plant_quads_id.json`
 `scripts/mapped_plant_quads_ks.json`
 `scripts/mapped_plant_quads_mt.json`
 `scripts/phytoplankton_size.json`
 `scripts/plant_comp_ok.json`
 `scripts/plant_occur_oosting.json`
 `scripts/portal.json`
 `scripts/veg_plots_sdl.json`

**Comment by ethanwhite** [comment]
I'm pretty sure we finished all of this a month and a half ago so I'm closing this. If I missed something feel free to reopen.
