### ISSUE TITLE
Error message: cannot import name 'urlretrieve' on Windows 10 home

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#865]
The following retriever command generates an error: 
```
retriever install csv mammal-community-db
=> Installing Mammal Community DataBase (Thibault et al. 2011)

Downloading MCDB_sites.csv...
cannot import name 'urlretrieve'
Done!
```
The file is not downloaded

**Comment by henrykironde** [comment]
@dmcglinn that is the problem with the server at http://esapubs.org
We have mentioned that in the #862 and therefore we are changing all ecological archive script URLS to their Figshare counterparts
Currently @zhangcandrew has offered to work on this, but I guess we shall need some more effort to get this done fast. I will chip in some time to get this up and running. Since you are using `mammal-community-db` I will fix this dataset right away.

**Comment by dmcglinn** [comment]
thanks @henrykironde !!

**Comment by nestorperez** [comment]
First of all, thank you for your really useful package. 
I have been trying to download FIA data, but the following error message appears:

`rdataretriever::install("forest-inventory-analysis", connection = "csv", data_dir = "data-raw/")`
=> Installing Forest Inventory and Analysis

Downloading REF_SPECIES.csv...
cannot import name 'urlretrieve'
Done!

Do you think is a server problem?
Thanks in advance!

**Comment by henrykironde** [comment]
@nestorperez, thanks for this report. 
I Just checked and it looks like they updated the files on `August 17, 2017` and the files (csv)are displaced.  They have not realized it yet.

**Comment by nestorperez** [comment]
Ok, I have to wait. Thanks for your quick response, @henrykironde.
