### ISSUE TITLE
an eBird Basic Dataset workflow

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#90]
Hey all,

I've mostly gotten the eBird data into a PostgreSQL/PostGIS database, and I thought I'd share my code with you in case you wanted to integrate it into something more robust with EcoDataRetriever.  If you know how to optimize it better, I'd love to hear what you come up with.

If you do decide to include it, please acknowledge Matt Jones and Jim Regetz, since they helped me through this.

Let me know if you have any questions!

Dave

PS the "world" data set unzips to be 50 gigabytes, so you'll probably want to work with something smaller...

```
-- Data file available via http://ebird.org/ebird/data/download

-- commands to extract the text file from the tarball:
   -- tar xvf ebd_relMay-2013.tar
   -- gunzip ebd_relMay-2013.txt.gz
-- WARNING: The resulting file is almost 50 gigabytes!

-- In retrospect, there's probably some premature optimization for some of these columns: if the data set changes,
-- it might be safer to use longer varchar arguments.
CREATE TABLE eBird (
  GLOBAL_UNIQUE_IDENTIFIER     char(50),      -- always 45-47 characters needed (so far)
  TAXONOMIC_ORDER              numeric,       -- Probably not needed
  CATEGORY                     varchar(20),   -- Probably 10 would be safe
  COMMON_NAME                  varchar(70),   -- Some hybrids have really long names
  SCIENTIFIC_NAME              varchar(70),   --  ''
  SUBSPECIES_COMMON_NAME       varchar(70),   --  ''
  SUBSPECIES_SCIENTIFIC_NAME   varchar(70),   --  ''
  OBSERVATION_COUNT            varchar(8),    -- Someone saw 1.3 million Auklets.
                                              -- Unfortunately, it can't be an integer 
                                              -- because some are just presence/absence
  BREEDING_BIRD_ATLAS_CODE     char(2),       -- need to confirm that these are always length 2
  AGE_SEX                      text,          -- Potentially long, but almost always blank
  COUNTRY                      varchar(50),   -- long enough for "Saint Helena, Ascension and Tristan da Cunha"
  COUNTRY_CODE                 char(2),       -- alpha-2 codes
  STATE_PROVINCE               varchar(50),   -- no idea if this is long enough? U.S. Virgin Islands may be almost 30
  SUBNATIONAL1_CODE            char(10),      -- looks standardized at 5 characters?
  COUNTY                       varchar(50),   -- who knows how long it could be
  SUBNATIONAL2_CODE            char(12),      -- looks standardized at 9 characters?
  IBA_CODE                     char(16),
  LOCALITY                     text,          -- unstructured/potentially long
  LOCALITY_ID                  char(10),      -- maximum observed so far is 8
  LOCALITY_TYPE                char(2),       -- short codes
  LATITUDE                     real,          -- Is this the appropriate level of precision?
  LONGITUDE                    real,          --    ''
  OBSERVATION_DATE             date,          -- Do I need to specify YMD somehow?
  TIME_OBSERVATIONS_STARTED    time,          -- How do I make this a time?
  TRIP_COMMENTS                text,          -- Comments are long, unstructured, 
  SPECIES_COMMENTS             text,          --    and inconsistent, but sometimes interesting
  OBSERVER_ID                  char(12),      -- max of 9 in the data I've seen so far
  FIRST_NAME                   text,          -- Already have observer IDs
  LAST_NAME                    text,          -- ''
  SAMPLING_EVENT_IDENTIFIER    char(12),      -- Probably want to index on this.
  PROTOCOL_TYPE                varchar(50),   -- Needs to be at least 30 for sure.
  PROJECT_CODE                 varchar(20),   -- Needs to be at least 10 for sure.
  DURATION_MINUTES             int,           -- bigint?
  EFFORT_DISTANCE_KM           real,          -- precision?
  EFFORT_AREA_HA               real,          -- precision?
  NUMBER_OBSERVERS             int,           -- just a small int
  ALL_SPECIES_REPORTED         int,           -- Seems to always be 1 or 0.  Maybe I could make this Boolean?
  GROUP_IDENTIFIER             varchar(10),   -- Appears to be max of 7 or 8
  APPROVED                     int,           -- Can be Boolean?
  REVIEWED                     int,           -- Can be Boolean?
  REASON                       char(17),      -- May need to be longer if data set includes unvetted data
  X                            text           -- Blank
);


COPY eBird
  FROM '/home/dharris/eBird/ebd_relMay-2013.txt' 
  HEADER
  CSV
  QUOTE E'\5'       -- The file has unbalanced quotes. Using an obscure character as a quote mark instead.
  DELIMITER E'\t';


-- Note: it's probably slightly faster to load postgis and add a geographic column first (see below).
-- I'm keeping the original ordering in this document for accuracy's sake.
CREATE INDEX ON eBird (sampling_event_identifier)

-- Example query: SELECT SCIENTIFIC_NAME FROM eBird WHERE SAMPLING_EVENT_IDENTIFIER = 'S9605852';
-- Example query: SELECT count(SCIENTIFIC_NAME) FROM eBird WHERE SAMPLING_EVENT_IDENTIFIER = 'S9605852';


CREATE EXTENSION postgis;
ALTER TABLE eBird ADD COLUMN geog geography(POINT,4326); -- I hope 4326 is correct...
UPDATE eBird SET geog = ST_GeogFromText('POINT(' || longitude || ' ' ||  latitude || ')');
CREATE INDEX geog_index ON eBird USING GIST (geog); 

-- Example query: find all the species within 1000 of my dorm:
-- SELECT SCIENTIFIC_NAME FROM eBird WHERE ST_DWithin(geog, ST_GeographyFromText('SRID=4326;POINT(-119.6972 34.4208)'), 1000);

-- Slightly fancier version:
-- SELECT DISTINCT SCIENTIFIC_NAME, COMMON_NAME FROM eBird 
--   WHERE ST_DWithin(geog, ST_GeographyFromText('SRID=4326;POINT(-119.855385 34.417239)'), 1000) 
--   ORDER BY SCIENTIFIC_NAME;
```

(Edited to add some amazing PostGIS queries and some better commets, etc.)

PS: After poking around a bit more, it looks like I should have used doubles rather than reals to store lat/lon.  I had misread the documentation about how much precision was used for reals.

**Comment by tomauer** [comment]
I've been spending the past few days trying to pull the eBird Basic Dataset into Postgres with no luck. I've gotten the Sampling Event Data file in, but the World File always ends with a set of different errors. If anyone has had any luck getting the eBird Basic Dataset or the eBird Reference Dataset into a database, please let me know.

@ethanwhite I'd be happy to help work on this and contributing to the retriever with help from someone who can troubleshoot Postgres errors better than I can.

**Comment by mbjones** [comment]
@tomauer what error are you getting?  I vaguely remember @davharris having some troubles with character encoding issues in the middle of the very large file. Segmenting the file and parallel processing it with a tool like iconv might help if you have issues like that. And as @davharris said above there were unbalanced quotes as well.  Are you seeing either of these errors in the ERD load?

**Comment by ethanwhite** [comment]
@tomauer we're starting work on getting eBird into the Retriever (see #252, #253, #254). I'd be curious to hear why you switched to the eBird Basic Dataset from the ERD, to help us prioritize our efforts. Also, is it correct that the Basic dataset has to be requested rather than downloaded from a stable link?

**Comment by tomauer** [comment]
@ethanwhite @davharris After a few more days of fighting with it, I was able to import the EBD World File and the EBD Sampling Data File into Postgres. Below are the SQL statements that I used to successfully do that. I had to first manually strip out two null characters in the dataset. I did that using EmEditor and the line number that Postgres gave me as an error when it hit the null characters. Some of my column types for new columns in this version might be a little weak or unnecessarily long.

I switched to the EBD because the structure of the ERD is absurd (every species as a column?!?!?!).  We don't have a need for the co-variate data at this point, so I didn't want to deal with the cross-tab aspect of the ERD either. To access the Basic dataset you do need to request access through eBird and the URL is locked. You have to be logged into eBird.

eBird World File
```
CREATE TABLE ebdrelNov2014 (
	GLOBAL_UNIQUE_IDENTIFIER	char(50),
	TAXONOMIC_ORDER 			numeric,
	CATEGORY 					varchar(20),
	COMMON_NAME 				varchar(70),
	SCIENTIFIC_NAME 			varchar(70),
	SUBSPECIES_COMMON_NAME 		varchar(70),
	SUBSPECIES_SCIENTIFIC_NAME 	varchar(70),
	OBSERVATION_COUNT 			varchar(8),
	BREEDING_BIRD_ATLAS_CODE 	char(2),
	AGE_SEX 					text,
	COUNTRY 					varchar(50),
	COUNTRY_CODE 				char(2),
	STATE_PROVINCE 				varchar(50),
	STATE_CODE 			char(10),
	COUNTY 						varchar(50),
	COUNTY_CODE 			char(12),
	IBA_CODE 					char(16),
	BCR_CODE				varchar(50),
	LOCALITY 					text,
	LOCALITY_ID 				char(10),
	LOCALITY_TYPE 				char(2),
	LATITUDE 					double precision,
	LONGITUDE 					double precision,
	OBSERVATION_DATE 			date,
	TIME_OBSERVATIONS_STARTED 	time,
	TRIP_COMMENTS 				text,
	SPECIES_COMMENTS 			text,
	OBSERVER_ID 				char(12),
	FIRST_NAME 					text,
	LAST_NAME 					text, 
	SAMPLING_EVENT_IDENTIFIER 	char(12),
	PROTOCOL_TYPE 				varchar(50),
	PROJECT_CODE 				varchar(20),
	DURATION_MINUTES 			int,
	EFFORT_DISTANCE_KM 			real,
	EFFORT_AREA_HA 				real,
	NUMBER_OBSERVERS 			int,
	ALL_SPECIES_REPORTED		int,
	GROUP_IDENTIFIER 			varchar(10),
	APPROVED 					int,
	REVIEWED 					int,
	REASON 						char(17),
	X 							text
);

COPY ebdrelNov2014
	FROM E'D:\\eBird\\ebd_relNov-2014.txt' 
	HEADER
	CSV
	QUOTE E'\5'
	DELIMITER E'\t'
;
```

eBird Sampling Data File
```
CREATE TABLE ebdsamplingrelnov2014 (
	COUNTRY 					varchar(50),
	COUNTRY_CODE 				varchar(50),
	STATE		 				varchar(50),
	STATE_CODE	 				char(10),
	COUNTY 						varchar(50),
	COUNTY_CODE		 			char(12),
	IBA_CODE 					char(16),
	BCR_CODE 					varchar(50),
	LOCALITY 					text,
	LOCALITY_ID 				char(10),
	LOCALITY_TYPE 				char(2),
	LATITUDE 					double precision,
	LONGITUDE 					double precision,
	OBSERVATION_DATE 			date,
	TIME_OBSERVATIONS_STARTED 	time,
	TRIP_COMMENTS 				text,
	OBSERVER_ID 				char(12),
	FIRST_NAME 					text,
	LAST_NAME 					text, 
	SAMPLING_EVENT_IDENTIFIER 	char(12),
	PROTOCOL_TYPE 				varchar(50),
	PROJECT_CODE 				varchar(20),
	DURATION_MINUTES 			int,
	EFFORT_DISTANCE_KM 			real,
	EFFORT_AREA_HA 				real,
	NUMBER_OBSERVERS 			int,
	ALL_SPECIES_REPORTED		int,
	GROUP_IDENTIFIER 			varchar(10),
	X 							text
);

COPY ebdsamplingrelnov2014
	FROM E'D:\\eBird\\ebd_sampling_relNov-2014.txt' 
	HEADER
	CSV
	ENCODING 'UTF8'
	QUOTE E'\b'
	DELIMITER E'\t'
;
```

**Comment by tomauer** [comment]
The other reason I didn't want to use the eBird Reference Dataset is that it only currently goes through 2012. We need as much data as we can get for our purposes and the eBird Basic Dataset has everything.

**Comment by ethanwhite** [comment]
Thanks for the feedback and insight into the table structure and issues with the data @tomauer. I also just heard back from the eBird folks and apparently having the ERD data public was actually a mistake and they are planning on putting it back behind the same access wall as the Basic Dataset is behind. As such I think we'll focus on the Observation Dataset (since it's publicly available; I'm almost done with this one) and working on supporting the Basic Dataset for fuller access to the data since it's has the core data and lacks the structural issues of ERD.

**Comment by ethanwhite** [comment]
eBird has basically pulled all of their data back behind closed doors, so I'm going to go ahead and close all of the eBird issues until such time as they decide to participate in the community in a more open way that we can readily help support.

**Comment by tomauer** [comment]
Hi @ethanwhite, are you referring to the eBird Basic Dataset (EBD) being behind the access wall? I now work at eBird and know that we don't want our data to be perceived as closed. Have you been in contact with anyone here? Or are you just basing this on the way EBD is accessed?

**Comment by ethanwhite** [comment]
@tomauer - I'd love to be wrong about this data being openly accessible. My perception is based on a combination of meaningful efforts to access the data over several years and some interactions with folks at eBird.

Originally we could find no way to access the data without creating a login, explaining why we wanted to use the data, getting permission, and then downloading a one time snapshot of the data. The eBird Observation Dataset then became available via DataONE, which was awesome and we started working on supporting it in the Data Retriever. We then found the eBird Reference Dataset openly available online and started working to support it, but out of an abundance of caution I emailed the eBird folks to make sure it was supposed to be public and they said no and removed the public access. Then later the DataONE copy of the eBird Observation Dataset disappeared without announcement and repeated queries to DataONE folks went unanswered.

So, that's the story. If I'm wrong and there are publicly accessible links to the eBird data that would be great and we'd be happy to support it again.

**Comment by ethanwhite** [comment]
I just did a little looking around and came across [this description](http://help.ebird.org/customer/portal/articles/1010524-can-i-download-raw-data-from-ebird-) of how to currently get the data. I then started the process for requesting the data again (I've done this in the past, but apparently that permission expires). In general I would say that while there's clearly some desire to make the data available to the community, which is great, that this is basically a closed dataset.

To download the data you need:

1. A login
2. Permission that requires explaining what you want to do with the data
3. Agreeing to a non-standard license agreement that prohibits redistribution of raw data (and even derived results without the non-standard license attached)

Both (2) and (3) make the dataset closed (i.e., not open) by any definition of "open data" that I'm aware of. I'm sure that there are good reasons for the decisions that eBird has made in this area, but one of the consequences is that since the data isn't open others can't readily build tools to make engaging with that data easier and more effective.

If you're interested in retaining the restrictions but allowing us and others to support the dataset then providing access to a permanently linked version of the data via an API key is an option. In that context we can instruct users to obtain a personal key and then store it where the software can access it. I've suggested this to a couple of other closed data sources that want people to use their data, but haven't had any takers yet. Once a valuable data source goes this route we'll put supporting it on the road map. My understanding is that the current eBird API only supports recent sightings. We'd be interested in supporting one of the full datasets.

**Comment by tomauer** [comment]
@ethanwhite You make a lot of good points about the "openness" of the data. We're talking about it here and may end up revising some of terms in the future. Most of this is quite a ways above me. Thanks for your feedback.

The current API does only support recent sightings, but there is a new API that is in the works that should have more features.

**Comment by ethanwhite** [comment]
Thanks @tomauer. I greatly appreciate your engaging with this. Let me know if there's anything I can do to help at any point.

**Comment by ses4j** [comment]
@tomauer Just FYI, I started with your table definition and COPY approach and have been using it to load eBird EBD data into PostgreSQL successfully.  I customized the COPY a little, added some indexes and such... Just posted a gist of it: https://gist.github.com/ses4j/22ccd5350eb28697d25c962d32879431
