### ISSUE TITLE
Script Versioning Protocol

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#908]
Right now we don't have an official protocol for changing or updating script version numbers. I think this is something we should add to the docs so that we have a guideline for future reference. 

Some things that have been discussed so far: 

| Changes in x. .         | Changes in  .x.            | Changes in  . .x  |
|:------------- |:-------------|:-----|
|Creation of new scripts | Adding new data to an existing script | Fixing small issues/typos within a script |

**Comment by ethanwhite** [comment]
Update: I recommended that we check in with the FrictionlessData folks on this, which @zhangcandrew has done (thanks @zhangcandrew!). They've recommended that we open a discussion of this over in their specs repo: https://github.com/frictionlessdata/specs/issues

When someone opens that issue if they could mention this issue then we'll have it tied in over here so that anyone who finds this will no where to look for ongoing discussion.

**Comment by zhangcandrew** [comment]
I'll go ahead and put that issue in now

**Comment by zhangcandrew** [comment]
I just saw the updates on frictionless data, so it looks like we should begin with a draft and see what they think. @ethanwhite do you have an idea in mind about how you want to approach this, or is this something that I should discuss with @henrykironde and begin to write out.

**Comment by henrykironde** [comment]
@zhangcandrew, we can have this discussion on how to proceed about this. First lets list all encounters that we have come across and then categorize them. We have mentioned three examples.

```
Creation of new scripts	
Adding new data to an existing script
Fixing small issues/typos within a script
```

Additionally we have:

1. Updating data in files
2. Change in the format of storage(e.g shift to zipped data)
3. Change in the location of the files(url, file names)
4. 

Will update with more occurrences tomorrow.

**Comment by ethanwhite** [comment]
This discussion resulted in the following addition to the Frictionless Data patterns:

https://specs.frictionlessdata.io/patterns/#data-package-version

It's not a perfect match since it envisions data and associated metadata being closely tied, which we often don't have, but we should try to follow this for now and then adjust if we encounter issues.
