### ISSUE TITLE
Empty datasets (BBS, others) in retriever / rdataretriever

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#947]
I've just installed retriever 2.0.0 and am trying to access the North American Breeding Bird Survey dataset.

Doing this in R with the `rdataretriever` yields a seemingly empty object:
```
> bbs = rdataretriever::fetch("breed-bird-survey")
> class(bbs)
[1] "list"
> str(bbs)
 Named list()
> names(bbs)
character(0)
> head(bbs)
named list()
```

In the command line, I got:
```
$ retriever install csv breed-bird-survey
=> Installing USGS North American Breeding Bird Survey
download() got an unexpected keyword argument 'debug'
Done!
```

I checked a few other datasets in R at random and found `plant-comp-ok`, `portal`, and `bird-size` to return the expected datasets but found `pantheria` and `socean-diet-data` to also return seemingly empty object.

This is on Windows 7 32-bit and R 3.4.0

**Comment by ethanwhite** [comment]
Sorry about that @ahhurlbert. Looks like some development code got merged into `master` instead of it's dev branch. I reverting it and just need to wait a couple of minutes for the tests to run. Once they're green I'll ping you again and then if you run:

```
retriever reset scripts
retriever update
```

you should be working again. I'll respond again in about 5 minutes once the tests have finished running and I've merged the revert. Thanks as always for reporting. You helped us catch this one really quickly.

**Comment by ethanwhite** [comment]
OK @ahhurlbert. You should be all set. Run 

```
retriever reset scripts
retriever update
```

and retry. If that works then we're in good shape and you can go ahead and close.

**Comment by ahhurlbert** [comment]
Sorry, should have chosen something other than BBS so that it wouldn't take so long to verify.

Looks good. Thank you!
