### ISSUE TITLE
Data file names are being converted to numbers upon download

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#955]
```
$retriever download portal
=> Installing Portal Project Data (Ernest et al. 2009)

Downloading 5603981...
100%  3 seconds
Downloading 3299483...

Downloading 3299474...
Copying 5603981 from C:\Users\danmc\.retriever\raw_data\portal
Copying 3299474 from C:\Users\danmc\.retriever\raw_data\portal
Copying 3299483 from C:\Users\danmc\.retriever\raw_data\portal
Done!
```
As can be seen by the output above the file names assigned are 5603981, 3299474, and 3299483 which are not the correct data file names.

**Comment by ethanwhite** [comment]
This is the result of Ecological Archives moving all of it's content to figshare. The file names are actually numbers now on the server (in the way that we're able to see them anyway). See, e.g., https://github.com/weecology/retriever/blob/master/scripts/portal.json#L184.

Renaming them would require additional development work. I guess the use case where this is problematic is for the `download` example you provided.

What are your thoughts on the value of making these changes and how we would choose the names?

**Comment by dmcglinn** [comment]
This is an unfortunate side effect, but not a problem I would put a lot of resources into solving. How does `install` know what the correct file names are? Another not great solution for the portal example would be downloading the zipped versions that figshare provides. For McGlinn et al. 2010 dataset we could use the following url:
https://ndownloader.figshare.com/articles/3547209/versions/1

unpack that file and then you would have the correct file names. This versioning system does get in the way if there are updated versions available.

**Comment by ethanwhite** [comment]
> How does install know what the correct file names are?

The names for each table are defined for `install` by the names in the scripts, so we get whatever we give it.

> Another not great solution for the portal example would be downloading the zipped versions that figshare provides.

Yeah, I don't love using the zipped versions since (until we implement #884) that would mean making these into `.py` scripts which is more difficult to maintain and contribute to.

I'm still struggling to understand the major use case here. `download` is designed for two things: 1) downloading non-tabular data files (not the case here); and 2) archiving files in their original state. Are you regularly using `download` for something where you need meaningful file names on for csv files where `install csv` isn't appropriate?

**Comment by ethanwhite** [comment]
I'm going to close this for the time being since I don't think that `download` should be getting a ton of direct use. Happy to have it reopened it someone wants to tackle it at some point.
