### ISSUE TITLE
socean_diet_data details could be updated

### ISSUE THREAD

**Issue by raymondben** [weecology/retriever#959]
Hi - I think the SO diet data set details could be usefully updated. First, the most direct reference is https://data.aad.gov.au/aadc/trophic/, not the figshare URL you are using. Also, this page points to the most up-to-date version of the data, which may not be propagated through to the ESA repository (and almost certainly not to the figshare copy). I think you're better off getting the data direct from the source.

**Comment by henrykironde** [comment]
@raymondben, thank you for this issue, We are going to go through your request and let you know. The reason we are using Figshare is because the ESA moved the files to Figshare. Since the authors have provided repositories for these data sets, we shall test and work as appropriate.
Also feel free to put in a PR for these changes, otherwise we shall do so.

**Comment by henrykironde** [comment]
Thanks for this issue, we do appreciate the contribution
